<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gzb</string>
	</array>
	<key>firstLineMatch</key>
	<string>^GAZLANG BYTECODE</string>
	<key>name</key>
	<string>GazLang bytecode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#file-header</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block-header</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#record</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#location</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#instruction</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\S.*$</string>
			<key>name</key>
			<string>invalid.illegal.gzb</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.block.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(top)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.arity.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.arity.gzb</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.in.gzb</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(fn)\s+([A-Za-z_][\w:.]*)\s+(\d+)\s+(\d+)(?:\s+(in)\s+([A-Za-z_][\w:.]*))?\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.gzb</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(?:(abstract)\s+)?(kind)\s+([A-Za-z_][\w:.]*)(?:\s+(extends)\s+([A-Za-z_][\w:.]*))?\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.lambda.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.index.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.arity.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.arity.gzb</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.in.gzb</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(lambda)\s+(\d+)\s+(\d+)\s+(\d+)(?:\s+(in)\s+([A-Za-z_][\w:.]*))?\s*$</string>
				</dict>
			</array>
		</dict>
		<key>file-header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.magic.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.version.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(GAZLANG\s+BYTECODE)\s+(\d+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(globals)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.globals.gzb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#global</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.gzb</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(statics)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.statics.gzb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#static-name</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.gzb</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>global</key>
		<dict>
			<key>match</key>
			<string>@\w+</string>
			<key>name</key>
			<string>variable.other.global.gzb</string>
		</dict>
		<key>instruction</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.label.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.label.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(LABEL)\s+(\S+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.jump.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.label.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(JMP|JZ|JNN|TRY)\s+(\S+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.catch.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.label.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CATCH_MATCH)\s+([A-Za-z_][\w:.]*)\s+(\S+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(RET|HALT|RETHROW|END_TRY|CATCH_VALUE)\s*$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(PUSH)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literal</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.gzb</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.call.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.count.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CALL)\s+([A-Za-z_][\w:.]*)\s+(\d+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.count.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CALL_BUILTIN)\s+(\w+)\s+(\d+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(PUSH_FN)\s+([A-Za-z_][\w:.]*)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.slot.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CHECK_PARAM)\s+(\d+)\s+([A-Za-z_][\w:]*(?:\|[A-Za-z_][\w:]*)*)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CHECK_RETURN)\s+([A-Za-z_][\w:]*(?:\|[A-Za-z_][\w:]*)*)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.count.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(NEW)\s+([A-Za-z_][\w:.]*)\s+(\d+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(PUSH_KIND|CALL_CONSTRUCTOR)\s+([A-Za-z_][\w:.]*)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.count.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CALL_PARENT)\s+([A-Za-z_][\w:.]*)\s+(\w+)\s+(\d+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(BIND_PARENT)\s+([A-Za-z_][\w:.]*)\s+(\w+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(LOAD_FIELD|SET_FIELD|GET_PROPERTY|GET_PROPERTY_QUIET|GET_PROPERTY_EXISTING|GET_METHOD)\s+(\w+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.count.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(CALL_METHOD)\s+(\d+)\s+(\w+)\s*$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((?:SET|DELETE)_PATH(?:_GLOBAL|_STATIC|_CAPTURED|_THIS)?)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\[k\]|\[\]</string>
							<key>name</key>
							<string>keyword.operator.path.gzb</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\.\.=</string>
							<key>name</key>
							<string>keyword.operator.path.gzb</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\.\w+</string>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\b\d+\b</string>
							<key>name</key>
							<string>constant.numeric.slot.gzb</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.gzb</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(LABEL|PUSH|POP|PRINT|LOAD|LOAD_QUIET|STORE|LOAD_GLOBAL|LOAD_QUIET_GLOBAL|STORE_GLOBAL|LOAD_CAPTURED|LOAD_QUIET_CAPTURED|STORE_CAPTURED|LOAD_STATIC|STORE_STATIC|ADD|SUB|MUL|DIV|MOD|POW|BIT_AND|BIT_OR|BIT_XOR|SHL|SHR|BIT_NOT|CONCAT|EQUALS|NOT_EQUALS|LT|LE|GT|GE|CMP|NOT|NO_MATCH|NO_CONDITION|CONCAT_ASSIGN|CONCAT_ASSIGN_GLOBAL|CONCAT_ASSIGN_CAPTURED|NEG|INC|DEC|JMP|JZ|JNN|NEW_ARRAY|ARRAY_PUSH|ARRAY_EXTEND|NEW_MAP|MAP_EXTEND|MAP_SET|KEY_CHECK|FOREACH_CHECK|DESTRUCTURE|INDEX_GET|INDEX_GET_QUIET|INDEX_GET_EXISTING|SET_PATH|SET_PATH_GLOBAL|SET_PATH_STATIC|SET_PATH_CAPTURED|SET_PATH_THIS|DELETE_PATH|DELETE_PATH_GLOBAL|DELETE_PATH_STATIC|DELETE_PATH_CAPTURED|DELETE_PATH_THIS|CALL|CALL_BUILTIN|CALL_VALUE|ARGC|CHECK_PARAM|CHECK_RETURN|RET|PUSH_FN|MAKE_CLOSURE|PUSH_KIND|NEW|CALL_CONSTRUCTOR|CALL_PARENT|BIND_PARENT|LOAD_THIS|LOAD_FIELD|SET_FIELD|GET_PROPERTY|GET_PROPERTY_QUIET|GET_PROPERTY_EXISTING|GET_METHOD|CALL_METHOD|TRY|END_TRY|CATCH_MATCH|CATCH_VALUE|RETHROW|HALT)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.instruction.gzb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\b\d+\b</string>
							<key>name</key>
							<string>constant.numeric.gzb</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.gzb</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*[A-Z][A-Z_]*\b.*$</string>
					<key>name</key>
					<string>invalid.illegal.unknown-instruction.gzb</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.gzb</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\\(?:[ntrvfe0\\"$\{]|x[0-9a-fA-F]{2}|u\{[0-9a-fA-F]{1,6}\})</string>
							<key>name</key>
							<string>constant.character.escape.gzb</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.gzb</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\['\\]</string>
							<key>name</key>
							<string>constant.character.escape.gzb</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash.gzb</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.gzb</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?\b0[xX][0-9a-fA-F]+\b</string>
					<key>name</key>
					<string>constant.numeric.hex.gzb</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict/>
					<key>match</key>
					<string>-?\b\d+(?:\.\d+(?:[eE][+-]?\d+)?|[eE][+-]?\d+)\b</string>
					<key>name</key>
					<string>constant.numeric.float.gzb</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict/>
					<key>match</key>
					<string>-?\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.gzb</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict/>
					<key>match</key>
					<string>\b(?:true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.gzb</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict/>
					<key>match</key>
					<string>=&gt;|,</string>
					<key>name</key>
					<string>punctuation.separator.gzb</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict/>
					<key>match</key>
					<string>[\[\]{}]</string>
					<key>name</key>
					<string>punctuation.section.gzb</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\S</string>
					<key>name</key>
					<string>invalid.illegal.gzb</string>
				</dict>
			</array>
		</dict>
		<key>location</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.location.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.path.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.line.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(@)(?:\s+("(?:[^"\\]|\\.)*"))?\s+(\d+)\s*$</string>
					<key>name</key>
					<string>meta.location.gzb</string>
				</dict>
			</array>
		</dict>
		<key>record</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.field.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.gzb</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(field)\s+(\w+)\s+([A-Za-z_][\w:.]*)(?:\s+(pub|kin))?(?:\s+((?!pub\b|kin\b)[A-Za-z_][\w:]*(?:\|[A-Za-z_][\w:]*)*))?\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.static.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.member.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(static)\s+(\w+)\s+([A-Za-z_][\w:]*(?:\|[A-Za-z_][\w:]*)*)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.method.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.method.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.gzb</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(method)\s+(\w+)\s+([A-Za-z_][\w:.]*)(?:\s+(pub|kin))?(?:\s+([A-Za-z_][\w:.]*))?\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.capture.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.local.gzb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.gzb</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.slot.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(capture)\s+(\$[#\w]+)\s+(local|captured)\s+(\d+)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.self.gzb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.local.gzb</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(self)\s+(\$[#\w]+)\s*$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(locals)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.locals.gzb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict/>
							<key>match</key>
							<string>\$[#\w]+</string>
							<key>name</key>
							<string>variable.other.local.gzb</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>invalid.illegal.gzb</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>static-name</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gzb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.accessor.gzb</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.member.gzb</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z_][\w:.]*)(::)(\w+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gzb</string>
	<key>uuid</key>
	<string>3c1d6f0e-2f4b-4c1a-8e2a-7b9d0c5e1f02</string>
</dict>
</plist>
