<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>GazLang template</string>
	<key>scopeName</key>
	<string>text.html.gazml</string>
	<key>uuid</key>
	<string>A0258A71-E9B4-4A1A-AB5A-26F3BF416E82</string>
	<key>fileTypes</key>
	<array>
		<string>gazml</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.namespace.gazml</string>
			<key>match</key>
			<string>^\s*(namespace)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.gazml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.namespace.gazml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.gazml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.import.gazml</string>
			<key>begin</key>
			<string>^\s*(?=import\b)</string>
			<key>end</key>
			<string>;|$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.gazml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gaz</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.directive.template.gazml</string>
			<key>begin</key>
			<string>^\s*(@template)\b(?:\s+(pub)\b)?</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.gazml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.gazml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.expression.gazml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gaz</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.directive.block.gazml</string>
			<key>begin</key>
			<string>^\s*(@(?:if|elseif|foreach))\s*(?=\()</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.gazml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.expression.gazml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gaz</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>meta.directive.gazml</string>
			<key>match</key>
			<string>^\s*(@(?:else|endif|endforeach))\s*$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.gazml</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>injections</key>
	<dict>
		<key>L:text.html.gazml - (meta.embedded.expression.gazml | comment.block.gazml)</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#echo</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.gazml</string>
			<key>begin</key>
			<string>\{\{--</string>
			<key>end</key>
			<string>--\}\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.gazml</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.gazml</string>
				</dict>
			</dict>
		</dict>
		<key>escaped</key>
		<dict>
			<key>name</key>
			<string>constant.character.escape.gazml</string>
			<key>match</key>
			<string>@\{\{</string>
		</dict>
		<key>raw</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.raw.gazml</string>
			<key>begin</key>
			<string>\{!!</string>
			<key>end</key>
			<string>!!\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.gazml</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.gazml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.expression.gazml source.gaz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gaz</string>
				</dict>
			</array>
		</dict>
		<key>echo</key>
		<dict>
			<key>name</key>
			<string>meta.embedded.echo.gazml</string>
			<key>begin</key>
			<string>\{\{</string>
			<key>end</key>
			<string>\}\}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.gazml</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.gazml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.expression.gazml source.gaz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gaz</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
